services:
  web:
    build: .
    ports:
      - "8888:80" # Application will run at http://localhost:8088
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  # MySql database
  db:
    image: mariadb:10.4
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: haasova_chirurgicka_ambulance
      MYSQL_USER: hospital_user
      MYSQL_PASSWORD: hospital_pass
    volumes:
      - db_data:/var/lib/mysql
      - ./haasova_chirurgicka_ambulance.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80" # phpMyAdmin will run at :8080
    environment:
      - PMA_HOST=db
      - PMA_USER=hospital_user
      - PMA_PASSWORD=hospital_pass
    depends_on:
      - db

volumes:
  db_data: